pub mod agents;
pub mod analyzers;
pub mod auth;
pub mod config;
pub mod context;
pub mod patch_check;
pub mod report;
pub mod rule_factory;
pub mod rule_packs;
pub mod skill_evolution;
pub mod skills;
pub mod spec_verify;
pub mod storage;
pub mod triage;
pub mod verify;

pub use agents::claude_code::*;
pub use agents::contract::*;
pub use agents::embedding::{cosine_similarity, embedding_from_bytes, embedding_to_bytes, fetch_embedding, parse_embedding_response};
pub use agents::local_llm::{local_llm_available, parse_chat_completion_response, LocalLlmBackend};
pub use agents::pi::{parse_pi_json_output, PiBackend};
pub use analyzers::apply_condition::ApplyCondition;
pub use analyzers::archgraph_check::run_archgraph_check;
pub use analyzers::architecture::{load_architecture_config, run_architecture_check};
pub use analyzers::ast_grep::{find_rule_definition, run_ast_grep, semantic_rule_ids, RuleDefinition};
pub use analyzers::bidi_check::run_bidi_control_character_check;
pub use analyzers::clippy::run_clippy;
pub use analyzers::churn::{detect_shotgun_surgery, run_divergent_change_check};
pub use analyzers::complexity::run_complexity_check;
pub use analyzers::practices::run_practices_check;
pub use analyzers::shadow_rules::{discover_shadow_rule_files, run_shadow_rules, ShadowFinding, ShadowRuleFile};
pub use analyzers::duplication::{run_cross_file_duplication_check, run_duplication_check};
pub use analyzers::golangci_lint::run_golangci_lint;
pub use analyzers::sarif::{ingest_sarif_file, parse_sarif_document};
pub use analyzers::dataflow_check::run_dataflow_check;
pub use analyzers::symindex_check::{run_symindex_check, run_symindex_check_with_tier4};
pub use auth::bitbucket_token::{verify_bitbucket_token, BitbucketUser};
pub use auth::credential_store::{CredentialStore, StoredVia};
pub use auth::github_device_flow::{run_device_flow, DeviceCodeResponse, PollOutcome};
pub use auth::{BITBUCKET_SERVICE, GITHUB_ACCOUNT, GITHUB_SERVICE};
pub use config::load_config;
pub use context::{collect_context, render_context_block, ContextItem};
pub use patch_check::parses_cleanly;
pub use report::*;
pub use rule_factory::bench::{run_bench, BenchReport, BenchVerdict, FpSmokeResult, SelfTestResult};
pub use rule_factory::draft::{draft_candidate, DraftOutcome};
pub use rule_factory::shadow::{classify_agreement, should_demote, should_promote, Agreement, AgentFindingRef, PromotionInputs};
pub use skill_evolution::mine::{draft_negative_guidance, mine_negative_guidance, write_proposal_file as write_skill_proposal_file, NegativeGuidanceSeed};
pub use skill_evolution::replay::{compare_replay, ReplayComparison};
pub use rule_factory::existing_rules::{find_similar_existing_rule, load_existing_rule_summaries, ExistingRuleMatch, ExistingRuleSummary};
pub use rule_factory::mine::{mine_candidates, write_seed_file, CandidateSeed, RepresentativeSnippet};
pub use rule_factory::mine_from_bitbucket_comments::{mine_from_bitbucket_pr_comments, resolve_bitbucket_repo_slug};
pub use rule_factory::mine_from_bugfix_commits::{mine_from_bugfix_commits, DEFAULT_MAX_COMMITS_SCANNED};
pub use rule_factory::mine_from_code::{mine_call_pair_conventions, CallPairConvention};
pub use rule_factory::mine_from_comments::mine_from_pr_comments;
pub use rule_factory::mine_from_suppressions::mine_from_suppressions;
pub use rule_packs::{default_rule_packs_cache_root, discover_pack_source, load_rule_packs_config, refresh_git_rule_packs, resolve_rule_packs, rule_packs_config_path, save_rule_packs_config, RefreshResult, ResolvedRulePack};
pub use skills::{compile_skill, discover_manifests, materialize_builtin_skill_to_disk, CompiledSkill};
pub use spec_verify::{draft_spec, parse_spec, run_spec_verify, DraftedSpec, SpecVerifyResult};
pub use storage::{
    append_event_log, events_from_report, feedback_event, filter_cost_records_since, load_run_cost_records, summarize_costs, sync_pull, sync_push, CostDashboard, EventRecord, FindingLookup,
    FpFeedbackRow, HistoryStore, KnownVerdict, MinedFindingRow, RunCostRecord,
};
pub use triage::*;
pub use verify::{run_verify_pass, select_for_verification, verify_finding, VerifyPassResult, VerifyResult};
